default_agent: drawingstate
agents:
  drawingstate:
    name: drawingstate
    entrypoint: /Users/jannis/Development/Outdated/SimpleMathDraw/state-mcp-server/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/jannis/Development/Outdated/SimpleMathDraw/state-mcp-server
    aws:
      execution_role: arn:aws:iam::645897315334:role/AmazonBedrockAgentCoreSDKRuntime-eu-central-1-f093d59e08
      execution_role_auto_create: false
      account: '645897315334'
      region: eu-central-1
      ecr_repository: 645897315334.dkr.ecr.eu-central-1.amazonaws.com/bedrock-agentcore-drawingstate
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: drawingstate-M3Ph5336gr
      agent_arn: arn:aws:bedrock-agentcore:eu-central-1:645897315334:runtime/drawingstate-M3Ph5336gr
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-drawingstate-builder
      execution_role: arn:aws:iam::645897315334:role/AmazonBedrockAgentCoreSDKCodeBuild-eu-central-1-f093d59e08
      source_bucket: bedrock-agentcore-codebuild-sources-645897315334-eu-central-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
